### ISSUE TITLE
Look and Feel: V4 Grey/Dark/Midnight Lua Editors: Console Pane Text is white on white background

### ISSUE THREAD

**Issue by unityconstruct** [damiensellier/CtrlrX#10]
# Look and Feel: V4 Grey/Dark/Midnight Lua Editors: Text is white on white background

- Lua Editor Text not legible on those themes [white text | white background ]
- likely should be [FF000000] vs [FFFFFFFF]
- Menu>Settings allows for changing background & font(not colorr), but doesn't adjust the console area so could use that for work around.
  - in the screencaps, I already changed the background color just to show the console color pallette isn't affected by those settings
- didn't find any CtrlrPanelEditor properties where it could be changed in-app
  - but it might be linked to one of those properties where end-user could inadvertently mess it up

- **V4 Light uses black text, so is simple workaround**

#### Lua Editor for each theme
![ctrlr-lua-editor-text-color-issue](https://github.com/damiensellier/CtrlrX/assets/40268430/10796f75-c2ea-455d-9fe7-75dd0b8ac1cc)

#### Lua Editor Settings
![image](https://github.com/damiensellier/CtrlrX/assets/40268430/486a5a14-4f3f-48e6-8847-dd1d904081e8)

**Comment by damiensellier** [comment]
oops thanks for noticing that. I'll fix it in the next release. 
Thanks for the feedback ;-)
Damien

**Comment by damiensellier** [comment]
I also checked the console window and it's the same problem. I will fix it asap.

**Comment by damiensellier** [comment]
SOLVED 
Update will be available in forthcoming v5.6.31

![Capture d’écran, le 2024-06-15 à 19 13 07](https://github.com/damiensellier/CtrlrX/assets/55164385/4b9d32dd-471c-4810-a3bd-9de5d73e4274)

**Comment by unityconstruct** [comment]
Nice work brother!
