### ISSUE TITLE
LUA mod:getMidiMessage():getProperty("midiMessageCtrlrNumber") crashing on PC

### ISSUE THREAD

**Issue by damiensellier** [damiensellier/CtrlrX#17]
local myNumber = mod:getMidiMessage():getProperty("midiMessageCtrlrNumber")
crashes on v5.6 on Windows. It works in 5.3.201.

NOTE : All _mod:getMidiMessage():getProperty()_ won't work on macOS and will return : 

`Error message: [string "sendCC"]:10: attempt to call method 'getProperty' (a nil value)`

```
sendCC = function(--[[ CtrlrModulator --]] mod --[[ number --]], value --[[ number --]], source)
    if panel:getBootstrapState() then
        return
    end
    local myNumber = mod:getMidiMessage():getProperty("midiMessageCtrlrNumber") -- CRASHES
  -- myNumber=15 -- WORKS
    panel:sendMidiMessageNow(CtrlrMidiMessage(string.format("B0 %.2x %.2x", myNumber, value)))
end

```

See @dnaldoog test panel for testing : [test midiMessageCtrlrNumber_1_0_2024-05-30_11-40.zip](https://github.com/RomanKubiak/ctrlr/files/15493013/test.midiMessageCtrlrNumber_1_0_2024-05-30_11-40.zip)

**Comment by dobo365** [comment]
Will have to check that one...

**Comment by damiensellier** [comment]
Comparer code v5.6.31 avec source v5.3.198

**Comment by damiensellier** [comment]
NOTE: 

Probably comes from a bad LuaBind defintion. Search for wrapForLua CtrlrLuaManager : 

```
void CtrlrModulator::wrapForLua (lua_State *L)
{
	using namespace luabind;

	module(L)
		[
			class_<CtrlrModulator, CtrlrLuaObject>("CtrlrModulator")
// ...
.def("getMidiMessage", (CtrlrMidiMessage &(CtrlrModulator::*)(void))&CtrlrModulator::getMidiMessagePtr)
		.def("getMidiMessage", (CtrlrMidiMessage &(CtrlrModulator::*)(const CtrlrMIDIDeviceType))&CtrlrModulator::getMidiMessagePtr)
// ...
```

**Comment by damiensellier** [comment]
CtrlrLuaManager L1143 was commented, I don't remember why : 

`.def("getProperty", (const var &(CtrlrModulator::*)(const Identifier&) const)&CtrlrModulator::getProperty) // Updated v5.6.31`

**Comment by damiensellier** [comment]
CtrlrModulator.cpp has all the mod properties

CtrlrMidiMessage.cpp has all the midiMessage properties
setProperty is declared
but 
getProperty is missing ??


requires something like that : 
CtrlrMidiMessageType CtrlrMidiMessage::getProperty() const
{
	//
}

**Comment by damiensellier** [comment]
Different properties of the midi message of the modulator : 

```
  <midi midiMessageType="9" midiMessageChannelOverride="0" midiMessageChannel="1"
        midiMessageCtrlrNumber="1.0" midiMessageCtrlrValue="0" midiMessageMultiList=""
        midiMessageSysExFormula=""/>
```

**Comment by damiensellier** [comment]
In Ctrlr 5.3.198 there's extra files for Lua which have been merged and deprecated : 

CtrlrModulatorProcessor.cpp
CtrlrModulatorProcessor.h

merged with  CtrlrManager.cpp

**Comment by damiensellier** [comment]
FIXED : 

![Capture d’écran, le 2024-12-17 à 18 47 25](https://github.com/user-attachments/assets/cb0d9283-6f20-4819-b627-8d043cb03eda)


[test midiMessageCtrlrNumber_1_0_2024-12-17_15-44.panel.zip](https://github.com/user-attachments/files/18172583/test.midiMessageCtrlrNumber_1_0_2024-12-17_15-44.panel.zip)

```


--
-- Called when a modulator value changes
-- @mod   http://ctrlr.org/api/class_ctrlr_modulator.html
-- @value    new numeric value of the modulator
--
sendCC = function(--[[ CtrlrModulator --]] mod --[[ number --]], value --[[ number --]], source)
    if panel:getBootstrapState() then
        return
    end
     local messageType = mod:getMidiMessage():getMidiMessageType()
    console("message Type Via getMidiMessageType: "..tostring(messageType))

     local messageTypeViaGetType = mod:getMidiMessage():getType()
    console("messageType Via getType: "..tostring(messageTypeViaGetType))

     local midiControllerNumber = mod:getMidiMessage():getNumber()
    console("midi Controller Number via getNumber: "..tostring(midiControllerNumber))

     local midiValue = mod:getMidiMessage():getValue()
    console("midi Value: "..tostring(midiValue))

     local messageSize = mod:getMidiMessage():getSize()
    console("message Size: "..tostring(messageSize))

     local midiMessageCtrlrNumberViaProp = mod:getMidiMessage():getProperty("midiMessageCtrlrNumber")
     console("midi Controller Number via getProperty: "..tostring(midiMessageCtrlrNumberViaProp))

    panel:sendMidiMessageNow(CtrlrMidiMessage(string.format("B0 %.2x %.2x", midiMessageCtrlrNumberViaProp, value)))
end
```



Both getNumber and getProperty() work from now on.

**Comment by damiensellier** [comment]
NOTE : 

CtrlrMidiMessage.h L118

`		//const var getProperty (const Identifier& name, const var &defaultReturnValue) const				{ return midiTree.getProperty (name, defaultReturnValue); } // Updated v5.6.31. Useless`

CtrlrMidiMessage.cpp L920

            .def("getProperty", (const var &(CtrlrMidiMessage::*)(const Identifier &) const) &CtrlrMidiMessage::getProperty) // Added v5.6.31
