### ISSUE TITLE
Improving Lua Method Editor settings

### ISSUE THREAD

**Issue by damiensellier** [damiensellier/CtrlrX#21]
Improving Lua Method Editor settings must be improved to set up custom elements colours. 

![Capture d’écran, le 2024-06-14 à 14 12 34](https://github.com/damiensellier/CtrlrX/assets/55164385/5122c9a2-9f6a-4c0b-be4c-550664ed86ac)

Ask for @dobo365 mods and merge code : 
![Code Editor Preferences](https://github.com/damiensellier/CtrlrX/assets/55164385/aa7d5596-42ee-4a47-a7e6-4d8f9dbf05ed)

**Comment by dobo365** [comment]
Renamed Settings to Preferences to be closer to other programs.
Adapted popup with extra properties. Use of color dialog popup. Better look (see picture above)

[Code editor Preferences.zip](https://github.com/user-attachments/files/16090178/Code.editor.Preferences.zip)

Source - UIcomponents - CtrlrLua - MethodEditor - CtrlrLuaMethodCodeEditorSettings.cpp and .h
CtrlrLuaMethodCodeEditor.cpp
CtrlrLuaMethodEditor.cpp
CtrlrIDs.h: add
    DECLARE_ID (luaMethodEditorLineNumbersBgColour);
    DECLARE_ID (luaMethodEditorLineNumbersColour);

Still to do: secure that the selected colors are kept through sessions.

**Comment by damiensellier** [comment]
Hi Dominique, I updated the files to implement the new LUA Method Editor look.

I get an error in  CtrlrLuaMethodEditor.cpp : 

```
void CtrlrLuaMethodEditor::resized()
{
	Component* comps[] = { methodTree, resizer, methodEditArea  };
	layoutManager.layOutComponents (comps, 3, 0, 0, getWidth(), getHeight(), false, true);
	methodTreeWidth = layoutManager.getItemCurrentAbsoluteSize(1); // Giving error
}
```

**methodTreeWidth = layoutManager.getItemCurrentAbsoluteSize(1);**

It doesn't know what it refers to.

Any clue if you added methodTreeWidth somewhere else before like in the CtrlrLuaMethodEditor.h ?

Thanks

**Comment by damiensellier** [comment]
NOTE : Requires storing the LUA Editor Properties in XML to recall settings with CtrlrX panel file or General preferences.

**Comment by dobo365** [comment]
> Hi Dominique @dobo365 , I updated the files to implement the new LUA Method Editor look.
> 
> I get an error in CtrlrLuaMethodEditor.cpp L125 :
> 
> ```
> void CtrlrLuaMethodEditor::resized()
> {
> 	Component* comps[] = { methodTree, resizer, methodEditArea  };
> 	layoutManager.layOutComponents (comps, 3, 0, 0, getWidth(), getHeight(), false, true);
> 	methodTreeWidth = layoutManager.getItemCurrentAbsoluteSize(1); // Giving error
> }
> ```
> 
> **methodTreeWidth = layoutManager.getItemCurrentAbsoluteSize(1);**
> 
> It doesn't know what it refers to.
> 
> Any clue if you added methodTreeWidth somewhere else before like in the CtrlrLuaMethodEditor.h ?
> 
> Thanks

Salut Damien!
No change there. Did you made a comparison of my CtrlrLuaMethodEditor.cpp and yours?
I added some lines in MenuItemSelected (in rows 1110+ but nothing related to size.
Did you use the adapted CtrlrLuaMethodCodeEditorSettings.cpp? Many changes in resized()...
Shall we have a call using Google Meet this w-e?
Would be easier to work together ;-)

**Comment by damiensellier** [comment]
Salut Dominique, j'ai tout mis comme tu avais fait. J'ai aussi ajouté des commentaires pour savoir ce qui a été ajouté pour cette version 5.6.31, ca aide.

J'ai commenté la ligne methodTreeWidth et ca construit bien l'app comme ça.

Je sais pas où tu as pris cette ligne parce que elle n'est pas là dans la version précédente : 
https://github.com/RomanKubiak/ctrlr/blob/8aa00d82127acda42ad9ac9b7b479461e9436aa4/Source/UIComponents/CtrlrLua/MethodEditor/CtrlrLuaMethodEditor.cpp#L121

Ca va être compliqué pour moi je repart ce weekend pendant toute la fin de l'année alors pas beaucoup disponible. J'avais un petit creux hier et aujourd'hui c'est pour ça que j'ai essayé d'avancer la dessus.

J'ai aussi regardé l'histoire des VST qui crashent soit disant à l'export si PanelIsDirty est 0. Sur mac tout va bien ca plante pas du tout peu import la valeur. Apparemment c'est que sur PC que ca bug.
https://github.com/damiensellier/CtrlrX/issues/37

Si tu peux essayer de ton côté d'exporter des instances à partir de CtrlrX VST avec un panel qui a le PanelIsDirty=0 et voir si ca plante ca m'aiderait parce que là j'ai pas de PC pour voir.

Je vais essayer d'arranger tout pour le début de l'année au cours de mes petits moments libres.

Tu peux aussi m'écrire par email. Tiens moi au courant ;)

Bonne soirée.

Damien
