### ISSUE TITLE
"Max exported VST params" ctrlrMaxExportedVstParameters not working as intended

### ISSUE THREAD

**Issue by damiensellier** [damiensellier/CtrlrX#31]
The parameter "Max exported VST params" ctrlrMaxExportedVstParameters is often useless.
If you export a panel as vst restricted instance, from the function getNumModulators() only the highest vstindex should set the limit. But it's not if the vstindex highest number is above 64. From what I can see, it falls back to the default settings from global Ctrlr preferences (64) because of **JMAX** comparator.

 "Max exported VST params" ctrlrMaxExportedVstParameters should be removed/commented.

and CtrlrProcessor::getNumParameters() needs to be updated : 

```
int CtrlrProcessor::getNumParameters()
{
    if (ctrlrManager)
        // return (jmax(ctrlrManager->getNumModulators(true), (int)overridesTree.getProperty (Ids::ctrlrMaxExportedVstParameters))); // Removed 5.6.31 because VST Host was returning 64 params most of the time since panels hardly have more than 64 parameters passed as vst controls
        return (ctrlrManager->getNumModulators(true)); // Updated v5.6.31.
    else
        return (CTRLR_DEFAULT_PARAMETER_COUNT);
}
```

**Comment by dobo365** [comment]
The question is: why is this needed?
I mean, we have the Export property to decide what to export and we have the VSTindex to sort them according to what we want to see in the DAW (Oscillators together then Filters then... for example).
If a limit would work, it would prevent exporting parameters marked as "Export" and this would be confusing.
Never experienced the limit of 64 but watched it as it was needed to have some .overrides file at a certain moment (tried that but never saw a diff). I have many panels with 100-200 exported parameters

**Comment by damiensellier** [comment]
I tried and it's not working anyway because if you load a panel from the stock vst, the parameters won't pass to the host so you'll get 0 control from the host.
I'll probably leave it as is or add statement if panel is single use max vstindex else use the current formula.
Ca permet surtout de pas avoir une liste de 64 parametres affichés pour les automations dans cubase. si j'en ai que deux utiles, il me map quand même les 62 autres sur mon controlleur ou clavier ce qui est pas pratique.

**Comment by damiensellier** [comment]
**FIXED** 
I got it working with the following statement : 

```
int CtrlrProcessor::getNumParameters() // Updated 5.6.31
{
    if (ctrlrManager)
        if (ctrlrManager->isSingleInstance())
        {
            return (ctrlrManager->getNumModulators(true)); // Added v5.6.31. 
        }
        else
        {
        return (jmax(ctrlrManager->getNumModulators(true), (int)overridesTree.getProperty (Ids::ctrlrMaxExportedVstParameters))); // Updated 5.6.31.
        }
    else
        return (CTRLR_DEFAULT_PARAMETER_COUNT);
}

```

When opening a panel in ctrlrx.vst we have 64 parameters ready to go as default : 

![Capture d’écran, le 2024-07-03 à 16 16 15](https://github.com/RomanKubiak/ctrlr/assets/55164385/19fbd59e-b0ab-4361-8617-cdd0b6415967)

When using a panel as vst instance we only have the max vstindex number of parameters passed to the host (here 4): 
![Capture d’écran, le 2024-07-03 à 16 18 52](https://github.com/RomanKubiak/ctrlr/assets/55164385/74b06036-d012-4d34-8e1a-80e17d89b4e9)

**Comment by damiensellier** [comment]
I don't have the 8 pages of useless parameters anymore on my MCU controller now, that's cool.
