### ISSUE TITLE
Should CtrlrX have its own .settings file or even own CtrlrX temp folder?

### ISSUE THREAD

**Issue by dobo365** [damiensellier/CtrlrX#34]
I was wondering if CtrlrX have its own .settings file or even own CtrlrX temp folder?
Switching back and forth between Ctrlr and CtrlrX may make the .settings file getting nuts...
This can be easily changed I think.
Let's think about it... Not a priority.

**Comment by damiensellier** [comment]
I already did it but reverted back, I don't remember why. I'll think about it and will write the reasons below :) It's 100% possible it's just 2 lines to change.

**Comment by damiensellier** [comment]
It seems to me that keeping the Ctrlr folder for panel resources and .settings is better because it allows switching from Ctrlr to CtrlrX without having to regenerate resources for each panels and plugins to this CtrlrX folder.

**Comment by damiensellier** [comment]
CtrlrX may have its .settings file for an official release if Ctrlr can be considered totally deprecated and replaced by CtrlrX.
