### ISSUE TITLE
Ctrlr window not showing up in Ableton Live

### ISSUE THREAD

**Issue by damiensellier** [damiensellier/CtrlrX#36]
Ctrlr window is not showing up in Ableton Live. (Reported by @dobo365)

Related files : 

https://github.com/damiensellier/CtrlrX/blob/master/Source/Plugin/CtrlrProcessorEditorForLive.cpp
https://github.com/damiensellier/CtrlrX/blob/master/Source/Plugin/CtrlrProcessorEditorForLive.h

**Comment by damiensellier** [comment]
The container component probably needs a addAndMakeVisible() declaration.

` addAndMakeVisible(CtrlrEditorWrapper = new CtrlrEditorWrapper(*this));`

ou 
`
 addAndMakeVisible(CtrlrEditorWrapper);`

**Comment by dobo365** [comment]
Please note that not all users have this issue so, not sure...
For me it works fine in my versions of Ableton Live Lite. It must work fine for other users of the full version.
But we can indeed try. Will be difficult to test a problem that I don't have ;-)
I can always send another version to the user with the issue...

**Comment by damiensellier** [comment]
Okay je pensais que c'était généralisé. Alors là ça devient compliqué. 
Je peux le rajouter pour voir si ça marche quand même ça n'engage à rien.

**Comment by damiensellier** [comment]
[CtrlrProcessorEditorForLive.cpp](https://github.com/damiensellier/CtrlrX/blob/master/Source/Plugin/CtrlrProcessorEditorForLive.cpp)

```
CtrlrEditorWrapper::CtrlrEditorWrapper(CtrlrProcessorEditorForLive &_liveEditorOwner, CtrlrProcessor *ownerFilter, CtrlrManager &ctrlrManager) 
	: DocumentWindow("Ctrlr", Colours::lightgrey, 0, true), liveEditorOwner(_liveEditorOwner)
{
	setTitleBarHeight(1);
    editor = new CtrlrEditor(ownerFilter, ctrlrManager);
    addAndMakeVisible(editor); // Added v5.6.31. Force wrapper visibility
	setContentOwned (editor, true);
	setAlwaysOnTop(true);
	centreWithSize (getWidth(),getHeight());
}
```

Also relies on property "Use the Editor Wrapper for VST Plugins"

**Comment by damiensellier** [comment]
NOTE : Please check update with LIVE ABLETON 12 FULL and LITE version

**Comment by damiensellier** [comment]
Ableton Live Lite 11 test failed with VST3

![Capture d’écran, le 2024-12-17 à 10 47 54](https://github.com/user-attachments/assets/bb711a5d-3cac-43ea-9e67-c93f18995f7b)

**Comment by damiensellier** [comment]
Ableton Live Lite 11 test succeeded with VST2
![Capture d’écran, le 2024-12-17 à 11 52 00](https://github.com/user-attachments/assets/2ce04189-08b6-46ad-a17c-098d260dcbf7)

**Comment by damiensellier** [comment]
Add : 

```
CtrlrProcessorEditorForLive::CtrlrProcessorEditorForLive(CtrlrProcessor *_filterOwner, CtrlrManager &_owner)
	: owner(_owner), filterOwner(_filterOwner), AudioProcessorEditor((AudioProcessor *)_filterOwner),
		wrapper(*this, filterOwner, owner)
{
	wrapper.setVisible (true);
    addAndMakeVisible(wrapper); // Added v5.6.31. Force wrapper visibility
	setSize (wrapper.getWidth(), 16);
	startTimer (50);
}
```

**Comment by damiensellier** [comment]
SOLVED : In projucer just disable "Midi Effect Plugin"
![Capture d’écran, le 2024-12-17 à 13 00 02](https://github.com/user-attachments/assets/04ec8441-814d-4a86-883d-a9df4c986534)


Requires updated ctrlrProcessor.cpp with I/O audio bus layout up to date : 
```

#ifndef JucePlugin_PreferredChannelConfigurations
bool CtrlrProcessor::isBusesLayoutSupported (const BusesLayout& layouts) const
{
  #if JucePlugin_IsMidiEffect
    ignoreUnused (layouts);
    return true;
  #else
    // This is the place where you check if the layout is supported.
    // In this template code we only support mono or stereo.
    // Some plugin hosts, such as certain GarageBand versions, will only
    // load plugins that support stereo bus layouts.
    if (layouts.getMainOutputChannelSet() != AudioChannelSet::mono()
     && layouts.getMainOutputChannelSet() != AudioChannelSet::stereo())
        return false;

    // This checks if the input layout matches the output layout
   #if ! JucePlugin_IsSynth
    if (layouts.getMainOutputChannelSet() != layouts.getMainInputChannelSet())
        return false;
   #endif

    return true;
  #endif
}
#endif

```
