### ISSUE TITLE
Exported Restricted Instances show Panel Tabs even if singleInstance

### ISSUE THREAD

**Issue by damiensellier** [damiensellier/CtrlrX#46]
Exported Restricted Instances show Panel Tabs even if singleInstance : 

![Capture d’écran, le 2024-12-22 à 12 04 34](https://github.com/user-attachments/assets/b57e6b13-da66-4b3e-8b55-da4d3d2c286f)

**Comment by dobo365** [comment]
Hmmm... Strange. I don't have this issue.
5.6.30.1G built on PC.
Maybe a Mac issue?

![image](https://github.com/user-attachments/assets/9dd8183d-d477-4c70-9051-e4ddbb9c1130)

**Comment by damiensellier** [comment]
@dobo365 it's coming from the mods we did recently for 5.6.31 to get the close button on tabs back.

I'll fix that, it's an easy one ;)

**Comment by damiensellier** [comment]
LOOK FOR : 

InstanceSingleRestriced

**Comment by damiensellier** [comment]
It comes from the fact previous Ctrlr versions was not reseting the ctrlrTabBarDepth for exported instances and was left blank. Which meant : 

setProperty (Ids::ctrlrTabBarDepth, 0);

This was causing the propertyPane not having tabs on export (top-right side)

To fix the problem I added  in CtrlrManagerInstance.cpp L36 :
setProperty (Ids::ctrlrTabBarDepth, 24); 

Now I have to set a condition if  InstanceSingleRestriced  then hide tabs / or setTabBarDepth = 0 in CtrlrDocumentPanel.cpp : 

```
void CtrlrDocumentPanel::activeDocumentChanged()
{
    CtrlrEditor *ed = dynamic_cast <CtrlrEditor*> (getParentComponent());
    if (ed)
    {
        ed->activeCtrlrChanged();
    }
    
    if (getCurrentTabbedComponent()) {
        
        getCurrentTabbedComponent()->setTabBarDepth(owner.getProperty(Ids::ctrlrTabBarDepth)); // Tab height for horizontal bar
        getCurrentTabbedComponent()->getTabbedButtonBar().setMinimumTabScaleFactor(1.0); // Min tab width ratio
        
        TabbedButtonBar &bar = getCurrentTabbedComponent()->getTabbedButtonBar();
        
        for (int i=0; i<bar.getNumTabs(); i++)
        {
            TabBarButton *button = bar.getTabButton (i); // Gets the panel tab button(i)
            
            if (button)
            {
                CtrlrDocumentPanelCloseButton *closeTabButton = new CtrlrDocumentPanelCloseButton("x"); // Added v5.6.30. Brings back the close button for panel tabs
                closeTabButton->addListener (this);
                closeTabButton->setSize(20, 20);
                closeTabButton->getProperties().set ("index", bar.indexOfTabButton(button));
                closeTabButton->setMouseCursor (MouseCursor::PointingHandCursor);
                button->setExtraComponent (closeTabButton, TabBarButton::afterText);
            }
        }
        
    }
}
```

**Comment by dobo365** [comment]
Hmmm...Strange as I also have the Tabs Close buttons...
Will look tomorrow to confirm.

**Comment by damiensellier** [comment]
FIXED on 22.12.2024 for v5.6.31

Unrestricted Instance : 
![Capture d’écran, le 2024-12-22 à 14 50 56](https://github.com/user-attachments/assets/53ae6120-69b5-4e47-8bb9-01d326977f44)

Restricted Instance 
![Capture d’écran, le 2024-12-22 à 14 50 43](https://github.com/user-attachments/assets/527240ed-df49-4781-872e-cd640c038fe8)
 


CtrlrDocumentPanel.cpp L48

```
void CtrlrDocumentPanel::activeDocumentChanged()
{
    CtrlrEditor *ed = dynamic_cast <CtrlrEditor*> (getParentComponent());
    if (ed)
    {
        ed->activeCtrlrChanged();
    }
    
    if (getCurrentTabbedComponent()) {
        
        if (owner.getInstanceMode() == InstanceSingle || owner.getInstanceMode() == InstanceSingleRestriced) // Added v5.6.31. Hides tabs on exported restricted instances
        {
            getCurrentTabbedComponent()->setTabBarDepth(0); // Tab height for horizontal bar
            getCurrentTabbedComponent()->getTabbedButtonBar().setMinimumTabScaleFactor(0); // Min tab width ratio
        }
        else
        {
            getCurrentTabbedComponent()->setTabBarDepth(owner.getProperty(Ids::ctrlrTabBarDepth)); // Tab height for horizontal bar
            getCurrentTabbedComponent()->getTabbedButtonBar().setMinimumTabScaleFactor(1.0); // Min tab width ratio
        }
        
        TabbedButtonBar &bar = getCurrentTabbedComponent()->getTabbedButtonBar();
        
        for (int i=0; i<bar.getNumTabs(); i++)
        {
            TabBarButton *button = bar.getTabButton (i); // Gets the panel tab button(i)
            
            if (button)
            {
                CtrlrDocumentPanelCloseButton *closeTabButton = new CtrlrDocumentPanelCloseButton("x"); // Added v5.6.30. Brings back the close button for panel tabs
                closeTabButton->addListener (this);
                closeTabButton->setSize(20, 20);
                closeTabButton->getProperties().set ("index", bar.indexOfTabButton(button));
                closeTabButton->setMouseCursor (MouseCursor::PointingHandCursor);
                button->setExtraComponent (closeTabButton, TabBarButton::afterText);
            }
        }
        
    }
}
```

**Comment by synthmania67** [comment]
this ist the error message of the validation when exporting an instance with version 5.6.31.03a: 
**TESTING OPEN TIMES:
COLD:
FATAL ERROR: OpenAComponent: result: -3000,0xFFFFF448**

**Comment by damiensellier** [comment]
Strange, it's working on my setup with AU : 
![Capture d’écran, le 2024-12-22 à 16 19 54](https://github.com/user-attachments/assets/5c213efd-59ca-428c-9d49-940a87dec965)

**Comment by synthmania67** [comment]
You have an intel mac, right? I think it´s a problem with Sonoma and these SILICON CPU only, because all older instances don´t work anymore unless you start in Rosetta mode. But this is not the solution. Developing a working CTRLR instance needs a Silicon Mac.

**Comment by damiensellier** [comment]
Sorry mate, this is where I have to close the helpdesk :) I already spent 5 hours of my Sunday to fix issues.

For this one, unfortunately I don't have a M4 and Sonoma yet so I can't help.

The only thing I can tell is from now on, AU will validate on mac intel or apple silicon prior Sonoma.

Since on your side you have all the setup, you can try run the AU on debug mode and see where it catches errors with breakpoints. 

Good luck

Damien

**Comment by synthmania67** [comment]
Sonoma changes everything. Most users always make the same mistake: as soon as Apple releases a new operating system, everyone rushes to install it without thinking.
Then, when nothing works, the developers of the software are berated.
That's the only reason I installed Sonoma in the first place. With Ventura, everything still worked perfectly...I don't want to know what doesn't work with Sequoia.
I'm slowly getting fed up with Apple...

Thank you very much for your help. Wish you a Merry Christmas.

**Comment by synthmania67** [comment]
Hi Damien, this is the crash report of the standalone app with SONOMA:
![Bildschirmfoto 2024-12-24 um 09 51 20](https://github.com/user-attachments/assets/0e428c26-5b3c-4eca-953e-f9d943926ed5)

**Comment by damiensellier** [comment]
@synthmania67 thanks! Can you post the /Volumes/Elements.crash  and  the ctrlrx.crash  ?

**Comment by damiensellier** [comment]
@synthmania67 Since you have Sonoma and I don't, I was wondering if you got the proper Native macOS FileChooser window when "exporting" an instance/restricted instance , or you had to switch to the JUCE FileChooser one?

On some older macOS (Catalina for exemple) Ctrlr was hanging when requesting the export from the menu.

Thanks!

PS : I opened a new issue for this macOS Sonoma crashing when closing problem : 

**https://github.com/damiensellier/CtrlrX/issues/49**

**Comment by synthmania67** [comment]
I´ve never changed the FileChooser. All is working fine as it should, but you´re right with Monterey and Ventura. I have no clue why.
About the discussion on the Juce page: I am looking forward to a solution and I hope there will be one.
