### ISSUE TITLE
Help me finish this simple lua method please

### ISSUE THREAD

**Issue by lowlou** [damiensellier/CtrlrX#5]
![155958319-560fc6e4-5be5-4251-9458-6295ef88b449](https://user-images.githubusercontent.com/70688865/155995740-2f235c91-7e3d-4c44-8e94-524b0ff6dfd6.png)

Hello. 

I try to make a method that turn off "panelMIDIpauseOut". 
Then a similar method that turn on "panelMIDIpauseOut".

I'll use them at "called before a snapshot is launched" and "called after a snapshot".

Please HELP ME because without this lua code, There is a bug (double midi bug) in all my setup that creates big problems with some of my synth/panel. 

I am pretty sure this is a solution to the problem I encounter. I have to manually toggle "panelMIDIpauseOut" dozens and dozens of time per session I can't stand it anymore. Each time I send a snapshot basically. 

I do not code, I only copy pasted some piece of code found on the old CTRLR forum on a thread about the double-midi bug. Don't expect any skills from me, I'm a total lua punk, I just want to solve this one bug with LUA, not become a coder. I'll consider a small donation to anybody that can help me.

**Comment by lowlou** [comment]
Where Am I supposed to seak for help now that the forum is closed really. How are musician supposed to do ? Musicians on Github ? Really ? Who thought it was a good idea ??

**Comment by lowlou** [comment]
Ok someone gave a solution on the CTRLR main Github, so this is a closed issue now :) Thanks !

**Comment by damiensellier** [comment]
Sorry I did not see your post. Issues section in the github world is more aimed at reporting bugs about the software itself.
As you mentionned the discussion section in the main Ctrlr github is the place to find help when working on a panel : https://github.com/RomanKubiak/ctrlr/discussions

Damien
